/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client;

import java.rmi.Naming;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;
import rmi.BankIf;
import rmi.CoordinatorIf;
import transaction.SubTransaction;

/**
 *
 * @author ricardo
 */
public class MainWindow extends javax.swing.JFrame {

    private final CoordinatorIf coordinator;
    private TransactionServerPing pingThread ;
    
    public List<BankIf> banks = new ArrayList<>();
    
    /**
     * Creates new form MainWindow
     * @param coordinator
     */
    public MainWindow(CoordinatorIf coordinator) {
        initComponents();
        this.coordinator = coordinator;
        pingThread = new TransactionServerPing(coordinator,this);
        pingThread.start();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ConsoleArea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jTextAmount = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jList1);

        jList2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jList2);

        jToggleButton1.setText("->");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton2.setText("<-");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Banco:");

        jLabel2.setText("Banco:");

        ConsoleArea.setColumns(20);
        ConsoleArea.setRows(5);
        jScrollPane3.setViewportView(ConsoleArea);

        jLabel3.setFont(new java.awt.Font("Liberation Mono", 1, 18)); // NOI18N
        jLabel3.setText("Cliente de Transações");

        jTextAmount.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00 €"))));
        jTextAmount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextAmount.setText("100");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBox1, 0, 144, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jToggleButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextAmount))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jComboBox2, 0, 162, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 224, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jTextAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jToggleButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO transfer conta1 para conta2
        if(jList1.getSelectedValue() != null && jList2.getSelectedValue() != null && Float.valueOf((String) jTextAmount.getValue())> 0){
            try {
                ConsoleArea.append("\n Started Transaction.");
                float amount = Float.valueOf((String) jTextAmount.getValue());
                String acc1 = jList1.getSelectedValue();
                String acc2 = jList2.getSelectedValue();
                String bank1 = (String) jComboBox1.getSelectedItem();
                String bank2 = (String) jComboBox2.getSelectedItem();
                
                SubTransaction trans1 = new SubTransaction(bank1, acc1, amount, false);
                SubTransaction trans2 = new SubTransaction(bank2, acc2, amount, true);
                ArrayList<SubTransaction> sts = new ArrayList<>();
                sts.add(trans1);
                sts.add(trans2);

                boolean answer = coordinator.transaction(sts);
                if(answer){
                    ConsoleArea.append("\nTransferência de "+bank1+"."+acc1+" para "+bank2+"."+acc2+" efectuada!");
                    System.out.println("Transferência de "+bank1+"."+acc1+" para "+bank2+"."+acc2+" efectuada!");
                }
                else{
                    ConsoleArea.append("\nERRO! Falhou transferência de "+bank1+"."+acc1+" para "+bank2+"."+acc2+"!");
                    System.out.println("ERRO! Falhou transferência de "+bank1+"."+acc1+" para "+bank2+"."+acc2+".");
                }
                
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        if(jList1.getSelectedValue() != null && jList2.getSelectedValue() != null && Float.valueOf((String) jTextAmount.getValue())> 0){
            try {
                float amount = Float.valueOf((String) jTextAmount.getValue());
                String acc1 = jList1.getSelectedValue();
                String acc2 = jList2.getSelectedValue();
                String bank1 = (String) jComboBox1.getSelectedItem();
                String bank2 = (String) jComboBox2.getSelectedItem();
                
                SubTransaction trans1 = new SubTransaction(bank1, acc1, amount, true);
                SubTransaction trans2 = new SubTransaction(bank2, acc2, amount, false);
                ArrayList<SubTransaction> sts = new ArrayList<>();
                sts.add(trans1);
                sts.add(trans2);

                boolean answer = coordinator.transaction(sts);
                if(answer){
                    ConsoleArea.append("\nTransferência de "+bank2+"."+acc2+" para "+bank1+"."+acc1+" efectuada!");
                    System.out.println("Transferência de "+bank2+"."+acc2+" para "+bank1+"."+acc1+" efectuada!");
                }
                else{
                    ConsoleArea.append("\nERRO! Falhou transferência de "+bank2+"."+acc2+" para "+bank1+"."+acc1+"!");
                    System.out.println("ERRO! Falhou transferência de "+bank2+"."+acc2+" para "+bank1+"."+acc1+".");
                }
                //this can be used in the application for further validation
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        String bank = (String) jComboBox1.getSelectedItem();
        try {
            List<String> accounts = coordinator.getAccounts(bank);
            if(accounts != null){
                DefaultListModel<String> model = new DefaultListModel<String>();
                for(String s:accounts){
                    model.addElement(s);
                }
                jList1.setModel(model);
            }
                
        } catch (RemoteException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        String bank = (String) jComboBox2.getSelectedItem();
        try {
            List<String> accounts = coordinator.getAccounts(bank);
            if(accounts != null){
                DefaultListModel<String> model = new DefaultListModel<String>();
                for(String s:accounts){
                    model.addElement(s);
                }
                jList2.setModel(model);
            }
        } catch (RemoteException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea ConsoleArea;
    public javax.swing.JComboBox<String> jComboBox1;
    public javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JFormattedTextField jTextAmount;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the banks
     */
    public List<BankIf> getBanks() {
        return banks;
    }

    /**
     * @param banks the banks to set
     */
    public void setBanks(List<String> banks)  {
        jComboBox1.removeAllItems();
        jComboBox2.removeAllItems();
        for(String b: banks){
            jComboBox1.addItem(b);
            jComboBox2.addItem(b);
        }
    }
}
